name: Example key vault flow

on:   
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@v2
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/get-keyvault-secrets@v1
      with: 
        keyvault: "containerappsvault"
        secrets: 'ACR_NAME, AZURE_SUBSCRIPTION_ID', 'AZURE_TENANT_ID', 'CONTAINERAPPS_ENVIRONMENT', 'RG_LOCATION', 'RG_NAME', 'SERVICE_PRINCIPAL_ID', 'SERVICE_PRINCIPAL_PASSWORD'
      id: myContainerappsSecret
    - uses: azure/docker-login@v1
      with:
        login-server: myregistry.azurecr.io
        username: ${{ steps.myContainerappsSecret.outputs.SERVICE_PRINCIPAL_ID }}
        password: ${{ steps.myContainerappsSecret.outputs.SERVICE_PRINCIPAL_PASSWORD }}
    - run: |
        docker build . -t myregistry.azurecr.io/myapp:${{ github.sha }}
        docker push myregistry.azurecr.io/myapp:${{ github.sha }}     
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'myapp'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'myregistry.azurecr.io/myapp:${{ github.sha }}'
