name: Customer Container Deploy
on:
  workflow_call:
    inputs:
      CUSTOMER-CONTAINER-NAME:
        required: true
        type: string
      CUSTOMER-ENV-NAME:
        required: false
        type: string
      RG_NAME:
        required: false
        type: string
      RG_LOCATION:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      REGISTRY_SERVER-NAME:
        required: true
        type: string
        
    secrets:
      azure-creds: 
        required: true

jobs:
    
    deploy:
   
      runs-on: ubuntu-latest

    
      steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure-creds }}
      - uses: Azure/get-keyvault-secrets@v1
        with: 
          keyvault: "containerappsvault"
          secrets: 'SERVICE-PRINCIPAL-ID, SERVICE-PRINCIPAL-PASSWORD'
        id: myAppsDeploySecrets

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp env create --name ${{  inputs.CUSTOMER-ENV-NAME }} --resource-group ${{  inputs.RG_NAME }} --location ${{  inputs.RG_LOCATION }}
            az containerapp create -n ${{ inputs.CUSTOMER-CONTAINER-NAME }} -g ${{ inputs.RG_NAME }} --image ${{ inputs.IMAGE_NAME }} --environment ${{  inputs.CUSTOMER-ENV-NAME }} --registry-server ${{ inputs.REGISTRY_SERVER-NAME }} --registry-username  ${{ steps.myAppsDeploySecrets.outputs.SERVICE-PRINCIPAL-ID }} --registry-password ${{ steps.myAppsDeploySecrets.outputs.SERVICE-PRINCIPAL-PASSWORD }} --target-port 80 --ingress external
