name: Container Apps Workflow
on:
  workflow_dispatch:

env:
  ACR_LOGON_SERVER: ${{ secrets.ACR_NAME }}.azurecr.io
  IMAGE_NAME: ${{ secrets.ACR_NAME }}.azurecr.io/webapp:${{ github.sha }}

jobs:
    build-deploy-image:
        
        runs-on: ubuntu-latest
        
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
      
        - name: 'Login to azure and fetch secrets from key vault'
          uses: Azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
         
        - uses: Azure/get-keyvault-secrets@v1
          with: 
            keyvault: "containerappsvault"
            secrets: 'AZURE-SUBSCRIPTION-ID, AZURE-TENANT-ID, SERVICE-PRINCIPAL-ID, SERVICE-PRINCIPAL-PASSWORD'
          id: myAppsBuildSecrets
          
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ env.ACR_LOGON_SERVER }}
            username: ${{ steps.myAppsBuildSecrets.outputs.SERVICE-PRINCIPAL-ID }}
            password: ${{ steps.myAppsBuildSecrets.outputs.SERVICE-PRINCIPAL-PASSWORD }}

        - name: Build and push container image to registry
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: |
             ${{ env.IMAGE_NAME }}
            file: dockersampledemo/Dockerfile
            context: ./

   
    deploy:
   


      needs: build-deploy-image
    
      uses: ./.github/workflows/customer-container-deploy.yml
      with:
        CUSTOMER-CONTAINER-NAME: Customer-PQR
        CUSTOMER-ENV-NAME: customersManagedEnv-PQR
      secrets: inherit
        
     

